apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gcr-clj-web
  namespace: production
spec:
  ingressClassName: nginx
  rules:
  - host: demo.atomist.com
    http:
      paths:
      - backend:
          service:
            name: gcr-clj-web
            port:
              number: 8080
        path: /clj2(/|$)(.*)
        pathType: Exact
