namespace: production
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
commonLabels:
  app.kubernetes.io/name: gcr-clj-web
images:
- name: gcr.io/personalsdm-216019/gcr-clj-web
  newTag: v11
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
decryption:
  provider: sops
  secretRef:
    name: sops-gpg
